name: flutter_foreground_plugin_example
description: Demonstrates how to use the flutter_foreground_plugin plugin.
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_foreground_plugin:
    path: ../

flutter:

  uses-material-design: true
