name: flutter_foreground_plugin
description: A foreground service plugin for Flutter. Support only Android (support Oreo). iOS not support yet.
version: 0.8.0
homepage: https://github.com/ChangJoo-Park/flutter_foreground_service_plugin

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: changjoopark.com.flutter_foreground_plugin
        pluginClass: FlutterForegroundPlugin
